# Ejercicio 1 - Práctica 2

Lea en Colab el archivo `flete-aereo-vacunas-covid19-al-2021-06-28.xlsx` y realice cualquier tarea de limpieza y/o adecuación del dataset que considere necesaria.

1. Según la información que se encuentra en la base de datos, ¿cuál fue el número de vuelo que realizó una mayor cantidad de fletes? Sugerencia: utilice el método `value_counts()` de la librería Pandas.

2. ¿Cuántos registros no contienen información sobre el número de vuelo?

3. Calcule el promedio de lo facturado en todos los vuelos realizados considerando únicamente los registros de viajes que se facturaron en USD según la información contenida en la columna `factura_moneda_monto`.

4. ¿Qué porcentaje de los vuelos realizados tuvieron como origen a Rusia o a China?

5. ¿Cuál es el vuelo más reciente de los que se tiene registro en el dataset? ¿Cuántos días transcurrieron entre el primer y el último vuelo realizados?

6. Escribir el archivo en formato `.parquet`.

# Lectura, limpieza y adecuación

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel('../datasets/flete-aereo-vacunas-covid19-al-2021-06-28.xlsx')
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Viajes para obtener vacunas de covid,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ultima actualización: Marzo-2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,organismo,expediente,financiamiento,acto_conclusión,descripción,prestador,CUIT,estado,factura_nro,factura_moneda_monto,guía_nro,guía_moneda_monto,fecha_guía,vuelo,bienes_transportados,proveedor_bienes_transportados,operación,comprador_donante,origen
4,Ministerio de Salud de la Nación,EX-2020-91578184- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-16691129-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011116,"USD 305.250,00",044-44032951,"USD 679,84",2020-12-23 00:00:00,1061,marking,Biointegrator LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia

In [3]:
'''
Notemos que las primeras filas son valores NAN. Vamos a usar la funcion "header" para abrir el dataset a partir
de la 4ta fila.
'''

df = pd.read_excel('../datasets/flete-aereo-vacunas-covid19-al-2021-06-28.xlsx', header=4)
df.head()

,organismo,expediente,financiamiento,acto_conclusión,descripción,prestador,CUIT,estado,factura_nro,factura_moneda_monto,guía_nro,guía_moneda_monto,fecha_guía,vuelo,bienes_transportados,proveedor_bienes_transportados,operación,comprador_donante,origen
0,Ministerio de Salud de la Nación,EX-2020-91578184- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-16691129-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011116,"USD 305.250,00",044-44032951,"USD 679,84",2020-12-23,1061,marking,Biointegrator LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
1,Ministerio de Salud de la Nación,EX-2020-91578184- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-16691129-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011116,"USD 302.250,00",044-44032940,"USD 304.570,16",2020-12-23,1061,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
2,Ministerio de Salud de la Nación,EX-2021-04601170- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24666588-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011206,"USD 302.250,00",044-44032973,"USD 302.250,00",2021-01-15,1061,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
3,Ministerio de Salud de la Nación,EX-2021-08460702- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24639513-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011296,NaN,044-44032984,"USD 268.655,94",2021-01-29,1063,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
4,Ministerio de Salud de la Nación,EX-2021-13211127- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24642675-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011370,"USD 303.075,00",044-44032995,"USD 303.075,00",2021-02-11,1065,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048571 entries, 0 to 1048570
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   organismo                       66 non-null     str
 1   expediente                      66 non-null     str
 2   financiamiento                  67 non-null     str
 3   acto_conclusión                 66 non-null     str
 4   descripción                     66 non-null     str
 5   prestador                       66 non-null     str
 6   CUIT                            66 non-null     str
 7   estado                          66 non-null     str
 8   factura_nro                     66 non-null     str
 9   factura_moneda_monto            64 non-null     str
 10  guía_nro                        66 non-null     str
 11  guía_moneda_monto               64 non-null     str
 12  fecha_guía                      66 non-null     datetime64[us]
 13  vuelo                           63 non-null     object
 14  bienes_transportados            66 non-null     str
 15  proveedor_bienes_transportados  66 non-null     str
 16  operación                       66 non-null     str
 17  comprador_donante               66 non-null     str
 18  origen                          66 non-null     str
dtypes: datetime64[us](1), object(1), str(17)
memory usage: 154.1+ MB

In [5]:
'''
Si observamos la columna de la variable "vuelo", podemos observar que hay un espacio a la derecha. 
Vamos a corregir esto.
'''

df.columns

Index(['organismo', 'expediente', 'financiamiento', 'acto_conclusión',
       'descripción', 'prestador', 'CUIT', 'estado', 'factura_nro',
       'factura_moneda_monto', 'guía_nro', 'guía_moneda_monto', 'fecha_guía',
       'vuelo ', 'bienes_transportados', 'proveedor_bienes_transportados',
       'operación', 'comprador_donante', 'origen'],
      dtype='str')

In [6]:
df.rename(columns={old_name: new_name for old_name,
            new_name in zip(df.columns, [col.replace(' ', '') for col in df.columns])},
            inplace=True)

df.columns

Index(['organismo', 'expediente', 'financiamiento', 'acto_conclusión',
       'descripción', 'prestador', 'CUIT', 'estado', 'factura_nro',
       'factura_moneda_monto', 'guía_nro', 'guía_moneda_monto', 'fecha_guía',
       'vuelo', 'bienes_transportados', 'proveedor_bienes_transportados',
       'operación', 'comprador_donante', 'origen'],
      dtype='str')

# Soluciones

In [7]:
'''
Item 1. Según la información que se encuentra en la base de datos,
¿cuál fue el número de vuelo que realizó una mayor cantidad de fletes?
'''

# Calculamos la frecuencia de cada vuelo
frecuencia_vuelos = df['vuelo'].value_counts()

print(frecuencia_vuelos)

vuelo
1061                   15
1063                   12
1065                    9
1051                    7
1081                    6
1067                    4
1069                    3
1501                    2
QR8351/16-QR8155/16     1
KL892                   1
KL701                   1
LH8433                  1
LH8434                  1
Name: count, dtype: int64

In [8]:
#Calcula el porcentaje de cada vuelo
porcentaje_vuelos = (frecuencia_vuelos / df['vuelo'].count())

print(porcentaje_vuelos)

#El vuelo 1061 fue el que realizó mayor cantidad de fletes.

vuelo
1061                   0.238095
1063                   0.190476
1065                   0.142857
1051                   0.111111
1081                   0.095238
1067                   0.063492
1069                   0.047619
1501                   0.031746
QR8351/16-QR8155/16    0.015873
KL892                  0.015873
KL701                  0.015873
LH8433                 0.015873
LH8434                 0.015873
Name: count, dtype: float64

In [9]:
'''
Item 2. ¿Cuántos registros no contienen información sobre el número de vuelo?
'''

# Vamos a ver qué tipo de datos tenemos en la columna vuelo
print(df.vuelo.unique())

# Contamos los registros donde "vuelo" es NaN
registros_sin_vuelo = df['vuelo'].isna().sum()

print(f"Número de registros sin información sobre el número de vuelo: {registros_sin_vuelo}")

# Este número es totalmente exagerado. Veamos bien el data frame.

[1061 1063 1065 'QR8351/16-QR8155/16' 1051 nan 1501 'KL892' 1067 'KL701'
 1069 1081 'LH8433' 'LH8434']
Número de registros sin información sobre el número de vuelo: 1048508

In [10]:
df

# Las ultimas filas son casi todos los valores NaN. Hay que limpiar esto.

,organismo,expediente,financiamiento,acto_conclusión,descripción,prestador,CUIT,estado,factura_nro,factura_moneda_monto,guía_nro,guía_moneda_monto,fecha_guía,vuelo,bienes_transportados,proveedor_bienes_transportados,operación,comprador_donante,origen
0,Ministerio de Salud de la Nación,EX-2020-91578184- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-16691129-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011116,"USD 305.250,00",044-44032951,"USD 679,84",2020-12-23,1061,marking,Biointegrator LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
1,Ministerio de Salud de la Nación,EX-2020-91578184- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-16691129-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011116,"USD 302.250,00",044-44032940,"USD 304.570,16",2020-12-23,1061,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
2,Ministerio de Salud de la Nación,EX-2021-04601170- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24666588-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011206,"USD 302.250,00",044-44032973,"USD 302.250,00",2021-01-15,1061,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
3,Ministerio de Salud de la Nación,EX-2021-08460702- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24639513-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011296,NaN,044-44032984,"USD 268.655,94",2021-01-29,1063,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
4,Ministerio de Salud de la Nación,EX-2021-13211127- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24642675-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011370,"USD 303.075,00",044-44032995,"USD 303.075,00",2021-02-11,1065,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1048567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1048568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1048569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1048570,NaN,NaN,Fuente Financiamiento 11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.dropna(axis=0,  thresh=3, inplace=True)
df

# Ahora el dataset tiene 66 filas y esto resulta razonable.

,organismo,expediente,financiamiento,acto_conclusión,descripción,prestador,CUIT,estado,factura_nro,factura_moneda_monto,guía_nro,guía_moneda_monto,fecha_guía,vuelo,bienes_transportados,proveedor_bienes_transportados,operación,comprador_donante,origen
0,Ministerio de Salud de la Nación,EX-2020-91578184- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-16691129-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011116,"USD 305.250,00",044-44032951,"USD 679,84",2020-12-23,1061,marking,Biointegrator LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
1,Ministerio de Salud de la Nación,EX-2020-91578184- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-16691129-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011116,"USD 302.250,00",044-44032940,"USD 304.570,16",2020-12-23,1061,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
2,Ministerio de Salud de la Nación,EX-2021-04601170- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24666588-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011206,"USD 302.250,00",044-44032973,"USD 302.250,00",2021-01-15,1061,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
3,Ministerio de Salud de la Nación,EX-2021-08460702- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24639513-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011296,NaN,044-44032984,"USD 268.655,94",2021-01-29,1063,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
4,Ministerio de Salud de la Nación,EX-2021-13211127- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24642675-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011370,"USD 303.075,00",044-44032995,"USD 303.075,00",2021-02-11,1065,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,Ministerio de Salud de la Nación,EX-2021-51336146- -APN-DD#MS,Fuente Financiamiento 13,RS-2021-54995747-APN-SGA#MS,Logística,DHL GLOBAL FORWARDING (ARGENTINA) S.A.,30-58471593-2,Cumplido,0028-00000784,"EUR 331.069,72",044-44033220,"EUR 331.069,72",2021-06-03,NaN,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
62,Ministerio de Salud de la Nación,EX-2021-51336146- -APN-DD#MS,Fuente Financiamiento 13,RS-2021-54995747-APN-SGA#MS,Seguro,DHL GLOBAL FORWARDING (ARGENTINA) S.A.,30-58471593-2,Cumplido,0028-00000785,"USD 19.700,23",044-44033220,"USD 19.700,23",2021-06-03,1061,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
63,Ministerio de Salud de la Nación,EX-2021-52119597- -APN-DD#MS,Fuente Financiamiento 13,RS-2021-56095206-APN-SGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011853,"USD 259.052,99",044-44033231,"USD 259.052,99",2021-06-08,1063,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
64,Ministerio de Salud de la Nación,EX-2021-56095077- -APN-DD#MS,Fuente Financiamiento 13,sin acto de conclusión,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011897,USD 428.000,044-44033264,"USD 14.687,34",2021-06-21,1065,sars-cov-2 vaccine (vero cell),Beijin Institute of Biological Phroducts co.,Adquisición,Secretaría de Acceso a la Salud,China
65,Ministerio de Salud de la Nación,EX-2021-56849335- -APN-DD#MS,Fuente Financiamiento 13,sin acto de conclusión,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011904,USD 428.000,044-44033275,USD 428.000,2021-06-22,1067,sars-cov-2 vaccine (vero cell),Beijin Institute of Biological Phroducts co.,Adquisición,Secretaría de Acceso a la Salud,China

In [12]:
'''
Item 3. Calcule el promedio de lo facturado en todos los  los vuelos
realizados considerando únicamente los registros de viajes que se facturaron en USD
según la información contenida en la columna factura_moneda_monto.
'''

# Extraemos las primeras tres letras y el número de la cadena
df['Moneda'] = df['factura_moneda_monto'].str.extract(r'([A-Z]+)')
df['Monto'] = df['factura_moneda_monto'].str.extract(r'(\d+\.?\d*,\d+)')

# Procesamos el número para eliminar el punto de los miles y reemplazamos la coma decimal con un punto
df['Monto'] = df['Monto'].str.replace('.', '').str.replace(',', '.')

# Convertimos la columna "Monto" de tipo 'object' a tipo numérico
df['Monto'] = pd.to_numeric(df['Monto'], errors='coerce')

# Filtramos las filas donde la moneda es USD
montos_usd = df.loc[df['Moneda'] == 'USD', 'Monto']

# Calculamos el promedio de lo facturado en EUR y USD
promedio_usd = montos_usd.mean()

# Imprimimos el promedio:
print("Promedio de lo facturado en USD:", round(promedio_usd,1))

Promedio de lo facturado en USD: 203181.2

In [13]:
'''
Item 4. ¿Qué porcentaje de los vuelos tuvo como origen a Rusia o a China?
'''

porcentaje_ruso_chino= len(df[(df['origen']=='Rusia')|(df['origen']=='China')])/len(df) * 100

print("El porcentaje de vuelos con origen Rusia/China es:", round(porcentaje_ruso_chino,2),"%")

El porcentaje de vuelos con origen Rusia/China es: 95.45 %

In [14]:
'''
Item 5. ¿Cuál es el vuelo más reciente de los que se tiene registro en el dataset?
¿Cuántos días transcurrieron entre el primer y el último vuelo?
'''

print('El ultimo vuelo fue: ',max(df['fecha_guía']))
print('El primer vuelo fue: ',min(df['fecha_guía']))
print('Cantidad de dias entre vuelos: ', max(df['fecha_guía'])- min(df['fecha_guía']))

El ultimo vuelo fue:  2021-06-22 00:00:00
El primer vuelo fue:  2020-12-23 00:00:00
Cantidad de dias entre vuelos:  181 days 00:00:00

In [18]:
'''
Item 6. Convertimos el data frame a formato parquet.
'''

# Convertir la columna 'vuelo' a tipo de datos cadena (str)
df['vuelo'] = df['vuelo'].astype(str)

# Escribir el DataFrame en formato Parquet
df.to_parquet('../outputs/vuelos_covid.parquet')